# file: test.sub
# author: victor.nadot@cea.fr
# company: CEA / DRF / IRFU / LDISC
# description: this file is doing that ...
# macros:
# - >> Mandatory
# - P: ${P} | PV prefix
# - >> Optional
# - EGU: ${EGU=Volts} | PV unit

file db/myDBfile.template {
    { P=xxx, Y=yyy}
    { P=aaa, Y=bbb}
}

file db/myDBfile.template {
    pattern { PREFIX,     SCAN }
            { ${ PREFIX } "1 second"}
            { ${ PREFIX } "3 second"}
}
